### PR TITLE
Service Layer - Normalise create methods to take project name as a string

### LINKED ISSUE #42: Service layer project getters
`ApplicationSoftwareService#create`, and most other services' `#create` methods, take a Project ID and assign it to a new ProjectEntity.
```kotlin
override fun create(projectId: Long, name: String) {
        val project = ProjectEntity()
        project.id = projectId
```
which I assume is just a lazy way of getting the ID into the database without having to check for project existence.

`NetworkService#create` takes a project name and fetches it from the database. 
```kotlin
    override fun create(name: String, projectName: String) {
        val project = projectService.get(projectName)

        if (project == null) {
            Logger.error("Could not find project with name [$projectName]")
            throw IllegalStateException("Project not found [$projectName]")
        } 
```
this should probably be done unilaterally

### PR DESCRIPTION
**Pull request by Sub-Xaero**
Closes #42

### CODE REVIEW

File: acropolis-service/src/main/kotlin/org/ephyra/acropolis/service/impl/ComputeInstanceService.kt [hunk 1]
```diff
@@ -1,26 +1,34 @@
...
 import org.ephyra.acropolis.service.api.IComputeInstanceService
+import org.ephyra.acropolis.service.api.IProjectService
+import org.slf4j.LoggerFactory
 import org.springframework.beans.factory.annotation.Autowired
 import org.springframework.stereotype.Service
 
 
 @Service
 class ComputeInstanceService : IComputeInstanceService {
+    val Logger = LoggerFactory.getLogger(IComputeInstanceService::class.java)
```
Comment (ThetaSinner) [inline acropolis-service/src/main/kotlin/org/ephyra/acropolis/service/impl/ComputeInstanceService.kt]: don't use interface type here
